# Generated by Django 4.2.16 on 2025-01-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='authuser',
            table='custom_auth_user',
        ),
    ]
